# Generated by Django 4.2.6 on 2023-10-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AddField(
            model_name="material",
            name="slug",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Просмотры"),
        ),
        migrations.AlterField(
            model_name="material",
            name="title",
            field=models.CharField(max_length=150, verbose_name="название"),
        ),
    ]
