# Generated by Django 4.2.6 on 2023-11-14 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_remove_product_vers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="catalog.version",
                verbose_name="Версия",
            ),
        ),
    ]
